colorize – Lib_VTK_IO
colorize Interface
3 statements
Source File
public interface colorize
Calls
Called by
Contents
Module Procedures
colorize_default
Module Procedures
private pure function colorize_default(string, color_fg, color_bg, style) result(colorized)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
character(len=*), intent(in), optional :: color_fg
character(len=*), intent(in), optional :: color_bg
character(len=*), intent(in), optional :: style
Return Value character(len=:), allocatable
Call graph
colorize calls colorize_default
colorize_default calls color_index, style_index, upper
colorize_str calls colorize
colors_samples calls colorize
styles_samples calls colorize
face_test_colors calls colorize
face_test_styles calls colorize
face_test_basic calls colors_samples, styles_samples