b64_decode_I2 – Lib_VTK_IO
b64_decode_I2 Subroutine
9 statements
Source File
private elemental subroutine b64_decode_I2(code, n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
integer(kind=I2P), intent(out) :: n
Calls
Called by
Contents
Source Code
b64_decode_I2
Source Code
   elemental subroutine b64_decode_I2(code, n)
   !< Decode a base64 code into a scalar number (I2P).
   !<
   !<```fortran
   !< use befor64
   !< use penf
   !< integer(I2P) :: scalar_I2
   !< call b64_decode(code='Nf8=',n=scalar_I2)
   !< print "(L1)", scalar_I2==-203_I2P
   !<```
   !=> T <<<
   character(*), intent(in)  :: code    !< Encoded scalar.
   integer(I2P), intent(out) :: n       !< Number to be decoded.
   integer(I1P), allocatable :: nI1P(:) !< One byte integer array containing n.
   allocate(nI1P(1:BYI2P)) ; nI1P = 0_I1P
   call decode_bits(code=code,bits=nI1P)
   n = transfer(nI1P,n)
   endsubroutine b64_decode_I2
Call graph
b64_decode_i2 calls decode_bits
b64_decode calls b64_decode_i2
b64_decode_up calls b64_decode_i2
decode calls b64_decode
volatile_doctest calls b64_decode