byte_size_chr – Lib_VTK_IO
byte_size_chr Function
5 statements
Source File
private elemental function byte_size_chr(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: i
Return Value integer(kind=I4P)
Called by
Contents
Source Code
byte_size_chr
Source Code
   elemental function byte_size_chr(i) result(bytes)
   !< Compute the number of bytes of a character variable.
   !<
   !<```fortran
   !< use penf
   !< print FI1P, byte_size('ab')
   !<```
   !=> 2 <<<
   character(*), intent(in) :: i     !< Character variable whose number of bytes must be computed.
   integer(I4P)             :: bytes !< Number of bytes of c.
   bytes = bit_size(i) / 8_I4P
   endfunction byte_size_chr
Call graph
byte_size calls byte_size_chr
b64_decode_string calls byte_size
b64_decode_string_a calls byte_size
b64_encode_string calls byte_size
b64_encode_string_a calls byte_size
volatile_doctest calls byte_size, b64_decode, b64_encode
b64_decode calls b64_decode_string, b64_decode_string_a
b64_encode calls b64_encode_string, b64_encode_string_a
b64_decode_up calls b64_decode_string, b64_decode_up_a, b64_decode_up
b64_decode_up_a calls b64_decode_string_a
b64_encode_up calls b64_encode_string, b64_encode_up_a, b64_encode_up
b64_encode_up_a calls b64_encode_string_a
decode calls b64_decode
encode calls b64_encode
encode_binary_dataarray1_rank1_i1p calls b64_encode
encode_binary_dataarray1_rank1_i2p calls b64_encode
encode_binary_dataarray1_rank1_i4p calls b64_encode
encode_binary_dataarray1_rank1_i8p calls b64_encode
encode_binary_dataarray1_rank1_r4p calls b64_encode
encode_binary_dataarray1_rank1_r8p calls b64_encode
encode_binary_dataarray1_rank2_i1p calls b64_encode
encode_binary_dataarray1_rank2_i2p calls b64_encode
encode_binary_dataarray1_rank2_i4p calls b64_encode
encode_binary_dataarray1_rank2_i8p calls b64_encode
encode_binary_dataarray1_rank2_r4p calls b64_encode
encode_binary_dataarray1_rank2_r8p calls b64_encode
encode_binary_dataarray1_rank3_i1p calls b64_encode
encode_binary_dataarray1_rank3_i2p calls b64_encode
encode_binary_dataarray1_rank3_i4p calls b64_encode
encode_binary_dataarray1_rank3_i8p calls b64_encode
encode_binary_dataarray1_rank3_r4p calls b64_encode
encode_binary_dataarray1_rank3_r8p calls b64_encode
encode_binary_dataarray1_rank4_i1p calls b64_encode
encode_binary_dataarray1_rank4_i2p calls b64_encode
encode_binary_dataarray1_rank4_i4p calls b64_encode
encode_binary_dataarray1_rank4_i8p calls b64_encode
encode_binary_dataarray1_rank4_r4p calls b64_encode
encode_binary_dataarray1_rank4_r8p calls b64_encode
encode_binary_dataarray3_rank1_i1p calls b64_encode
encode_binary_dataarray3_rank1_i2p calls b64_encode
encode_binary_dataarray3_rank1_i4p calls b64_encode
encode_binary_dataarray3_rank1_i8p calls b64_encode
encode_binary_dataarray3_rank1_r4p calls b64_encode
encode_binary_dataarray3_rank1_r8p calls b64_encode
encode_binary_dataarray3_rank3_i1p calls b64_encode
encode_binary_dataarray3_rank3_i2p calls b64_encode
encode_binary_dataarray3_rank3_i4p calls b64_encode
encode_binary_dataarray3_rank3_i8p calls b64_encode
encode_binary_dataarray3_rank3_r4p calls b64_encode
encode_binary_dataarray3_rank3_r8p calls b64_encode
encode_binary_dataarray6_rank1_i1p calls b64_encode
encode_binary_dataarray6_rank1_i2p calls b64_encode
encode_binary_dataarray6_rank1_i4p calls b64_encode
encode_binary_dataarray6_rank1_i8p calls b64_encode
encode_binary_dataarray6_rank1_r4p calls b64_encode
encode_binary_dataarray6_rank1_r8p calls b64_encode
encode_binary_dataarray6_rank3_i1p calls b64_encode
encode_binary_dataarray6_rank3_i2p calls b64_encode
encode_binary_dataarray6_rank3_i4p calls b64_encode
encode_binary_dataarray6_rank3_i8p calls b64_encode
encode_binary_dataarray6_rank3_r4p calls b64_encode
encode_binary_dataarray6_rank3_r8p calls b64_encode
encode_binary_dataarray calls encode_binary_dataarray1_rank1_i1p, encode_binary_dataarray1_rank1_i2p, encode_binary_dataarray1_rank1_i4p, encode_binary_dataarray1_rank1_i8p, encode_binary_dataarray1_rank1_r4p, encode_binary_dataarray1_rank1_r8p, encode_binary_dataarray1_rank2_i1p, encode_binary_dataarray1_rank2_i2p, encode_binary_dataarray1_rank2_i4p, encode_binary_dataarray1_rank2_i8p, encode_binary_dataarray1_rank2_r4p, encode_binary_dataarray1_rank2_r8p, encode_binary_dataarray1_rank3_i1p, encode_binary_dataarray1_rank3_i2p, encode_binary_dataarray1_rank3_i4p, encode_binary_dataarray1_rank3_i8p, encode_binary_dataarray1_rank3_r4p, encode_binary_dataarray1_rank3_r8p, encode_binary_dataarray1_rank4_i1p, encode_binary_dataarray1_rank4_i2p, encode_binary_dataarray1_rank4_i4p, encode_binary_dataarray1_rank4_i8p, encode_binary_dataarray1_rank4_r4p, encode_binary_dataarray1_rank4_r8p, encode_binary_dataarray3_rank1_i1p, encode_binary_dataarray3_rank1_i2p, encode_binary_dataarray3_rank1_i4p, encode_binary_dataarray3_rank1_i8p, encode_binary_dataarray3_rank1_r4p, encode_binary_dataarray3_rank1_r8p, encode_binary_dataarray3_rank3_i1p, encode_binary_dataarray3_rank3_i2p, encode_binary_dataarray3_rank3_i4p, encode_binary_dataarray3_rank3_i8p, encode_binary_dataarray3_rank3_r4p, encode_binary_dataarray3_rank3_r8p, encode_binary_dataarray6_rank1_i1p, encode_binary_dataarray6_rank1_i2p, encode_binary_dataarray6_rank1_i4p, encode_binary_dataarray6_rank1_i8p, encode_binary_dataarray6_rank1_r4p, encode_binary_dataarray6_rank1_r8p, encode_binary_dataarray6_rank3_i1p, encode_binary_dataarray6_rank3_i2p, encode_binary_dataarray6_rank3_i4p, encode_binary_dataarray6_rank3_i8p, encode_binary_dataarray6_rank3_r4p, encode_binary_dataarray6_rank3_r8p
write_dataarray1_rank1_i1p calls encode_binary_dataarray
write_dataarray1_rank1_i2p calls encode_binary_dataarray
write_dataarray1_rank1_i4p calls encode_binary_dataarray
write_dataarray1_rank1_i8p calls encode_binary_dataarray
write_dataarray1_rank1_r4p calls encode_binary_dataarray
write_dataarray1_rank1_r8p calls encode_binary_dataarray
write_dataarray1_rank2_i1p calls encode_binary_dataarray
write_dataarray1_rank2_i2p calls encode_binary_dataarray
write_dataarray1_rank2_i4p calls encode_binary_dataarray
write_dataarray1_rank2_i8p calls encode_binary_dataarray
write_dataarray1_rank2_r4p calls encode_binary_dataarray
write_dataarray1_rank2_r8p calls encode_binary_dataarray
write_dataarray1_rank3_i1p calls encode_binary_dataarray
write_dataarray1_rank3_i2p calls encode_binary_dataarray
write_dataarray1_rank3_i4p calls encode_binary_dataarray
write_dataarray1_rank3_i8p calls encode_binary_dataarray
write_dataarray1_rank3_r4p calls encode_binary_dataarray
write_dataarray1_rank3_r8p calls encode_binary_dataarray
write_dataarray1_rank4_i1p calls encode_binary_dataarray
write_dataarray1_rank4_i2p calls encode_binary_dataarray
write_dataarray1_rank4_i4p calls encode_binary_dataarray
write_dataarray1_rank4_i8p calls encode_binary_dataarray
write_dataarray1_rank4_r4p calls encode_binary_dataarray
write_dataarray1_rank4_r8p calls encode_binary_dataarray
write_dataarray3_rank1_i1p calls encode_binary_dataarray
write_dataarray3_rank1_i2p calls encode_binary_dataarray
write_dataarray3_rank1_i4p calls encode_binary_dataarray
write_dataarray3_rank1_i8p calls encode_binary_dataarray
write_dataarray3_rank1_r4p calls encode_binary_dataarray
write_dataarray3_rank1_r8p calls encode_binary_dataarray
write_dataarray3_rank3_i1p calls encode_binary_dataarray
write_dataarray3_rank3_i2p calls encode_binary_dataarray
write_dataarray3_rank3_i4p calls encode_binary_dataarray
write_dataarray3_rank3_i8p calls encode_binary_dataarray
write_dataarray3_rank3_r4p calls encode_binary_dataarray
write_dataarray3_rank3_r8p calls encode_binary_dataarray
write_dataarray6_rank1_i1p calls encode_binary_dataarray
write_dataarray6_rank1_i2p calls encode_binary_dataarray
write_dataarray6_rank1_i4p calls encode_binary_dataarray
write_dataarray6_rank1_i8p calls encode_binary_dataarray
write_dataarray6_rank1_r4p calls encode_binary_dataarray
write_dataarray6_rank1_r8p calls encode_binary_dataarray
write_dataarray6_rank3_i1p calls encode_binary_dataarray
write_dataarray6_rank3_i2p calls encode_binary_dataarray
write_dataarray6_rank3_i4p calls encode_binary_dataarray
write_dataarray6_rank3_i8p calls encode_binary_dataarray
write_dataarray6_rank3_r4p calls encode_binary_dataarray
write_dataarray6_rank3_r8p calls encode_binary_dataarray